Feature/products
Volodymyr-Mospan/command-project-html-css-fson64 pull request #3
Opened 2022-10-08 13:28 UTC by Yulia-Safonova-85

зробила розмітку  html Feature/products, завантажила оптимізовані картинки 1x та 2x з секції Product у папку images

2022-10-08 18:17 UTC, Volodymyr-Mospan requested changes
Перевірив. На доопрацювання.

2022-10-08 18:17 UTC, Volodymyr-Mospan commented on src/partials/products.html
> +    <label class="section__lable">100% natural</label>
Тег <lable> треба замінити, я пропоную тег <p> - тоді на нього одразу стануть стилі що я прописав у _common.scss

2022-10-08 20:33 UTC, Yulia-Safonova-85 commented on src/partials/products.html
> +    <label class="section__lable">100% natural</label>
виправлено

2022-10-09 08:46 UTC, Volodymyr-Mospan requested changes
Перевірив. На доопрацювання

2022-10-09 08:46 UTC, Volodymyr-Mospan commented on src/partials/products.html
> +              <use href=""></use>
href пустий - це видасть помилку

2022-10-09 08:46 UTC, Volodymyr-Mospan commented on src/partials/products.html
> +              <use href=""></use>
href пустий - це видасть помилку

2022-10-09 08:46 UTC, Volodymyr-Mospan commented on src/partials/products.html
> +              <use href=""></use>
href пустий - це видасть помилку

2022-10-09 13:48 UTC, Yulia-Safonova-85 commented on src/partials/products.html
> +              <use href=""></use>
прибрала

2022-10-09 13:48 UTC, Yulia-Safonova-85 commented on src/partials/products.html
> +              <use href=""></use>
прибрала

2022-10-09 15:06 UTC, Volodymyr-Mospan requested changes
Перевірив. На доопрацювання.

2022-10-09 15:06 UTC, Volodymyr-Mospan commented on src/partials/products.html
> +    <ul class="section__list">
Зміни section__list і section__item на products_list і products_item відповідно, оскільки section__ це дуже загально, наче як для всіх секцій.

2022-10-09 15:06 UTC, Volodymyr-Mospan commented on src/partials/products.html
> +      <li class="section__item">
Зміни section__list і section__item на products_list і products_item відповідно, оскільки section__ це дуже загально, наче як для всіх секцій.

2022-10-09 15:06 UTC, Volodymyr-Mospan commented on src/partials/products.html
> +      <li class="section__item">
Зміни section__list і section__item на products_list і products_item відповідно, оскільки section__ це дуже загально, наче як для всіх секцій.

2022-10-09 15:06 UTC, Volodymyr-Mospan commented on src/partials/products.html
> +      <li class="section__item">
Зміни section__list і section__item на products_list і products_item відповідно, оскільки section__ це дуже загально, наче як для всіх секцій.

2022-10-09 15:06 UTC, Volodymyr-Mospan commented on src/sass/_products.scss
> +.section__lable {
На загальні стилі використовуй моддифікатор ( section__lable--dark), інакше всі прописані тобою стилі підуть і на подальші (нижні) секції.

2022-10-09 15:06 UTC, Volodymyr-Mospan commented on src/sass/_products.scss
> +.section__title {
На загальні стилі використовуй моддифікатор ( section__title--dark), інакше всі прописані тобою стилі підуть і на подальші (нижні) секції.

2022-10-09 15:06 UTC, Volodymyr-Mospan commented on src/sass/_products.scss
> +.section__list {
Зиіни section__list і section__item на products_list і products_item відповідно, оскільки section__ це дуже загально, наче як для всіх секцій.

2022-10-09 15:06 UTC, Volodymyr-Mospan commented on src/sass/_products.scss
> +.section__item {
Зиіни section__list і section__item на products_list і products_item відповідно, оскільки section__ це дуже загально, наче як для всіх секцій.

2022-10-10 10:18 UTC, Yulia-Safonova-85 commented on src/sass/_products.scss
> +.section__list {
замінила

2022-10-10 10:19 UTC, Yulia-Safonova-85 commented on src/sass/_products.scss
> +.section__title {
зробила

2022-10-10 11:07 UTC, Volodymyr-Mospan approved these changes
Перевірив. Прийнято.

2022-10-10 11:07 UTC, merged